CREATE TABLE students (
  Name TEXT,
  Date_of_Birth DATE,
  Graduating_Year INTEGER,
  Gender TEXT,
  Postal_Code TEXT,

  Personal_Cumulative_Grade_Average INTEGER,
  Personal_English_Average INTEGER,
  Personal_French_Average INTEGER,
  Personal_Math_Average INTEGER,
  Personal_Science_Average INTEGER,
  Personal_History_Average INTEGER,
  Personal_Physical_Education_Average INTEGER,
  Personal_Arts_Music_Average INTEGER,
  Personal_ERC_Average INTEGER,

  High_School_Rating REAL,

  Class_Cumulative_Grade_Average INTEGER,
  Class_English_Average INTEGER,
  Class_French_Average INTEGER,
  Class_Math_Average INTEGER,
  Class_Science_Average INTEGER,
  Class_History_Average INTEGER,
  Class_Physical_Education_Average INTEGER,
  Class_Arts_Music_Average INTEGER,
  Class_ERC_Average INTEGER,

  Teacher_English_Average INTEGER,
  Teacher_French_Average INTEGER,
  Teacher_Math_Average INTEGER,
  Teacher_Science_Average INTEGER,
  Teacher_History_Average INTEGER,
  Teacher_Physical_Education_Average INTEGER,
  Teacher_Arts_Music_Average INTEGER,
  Teacher_ERC_Average INTEGER,

  School_Cumulative_Grade_Average INTEGER,
  School_English_Average INTEGER,
  School_French_Average INTEGER,
  School_Math_Average INTEGER,
  School_Science_Average INTEGER,
  School_History_Average INTEGER,
  School_Physical_Education_Average INTEGER,
  School_Arts_Music_Average INTEGER,
  School_ERC_Average INTEGER,

  Region_Cumulative_Grade_Average INTEGER,
  Region_English_Average INTEGER,
  Region_French_Average INTEGER,
  Region_Math_Average INTEGER,
  Region_Science_Average INTEGER,
  Region_History_Average INTEGER,
  Region_Physical_Education_Average INTEGER,
  Region_Arts_Music_Average INTEGER,
  Region_ERC_Average INTEGER,

  Provincial_Cumulative_Grade_Average INTEGER,
  Provincial_English_Average INTEGER,
  Provincial_French_Average INTEGER,
  Provincial_Math_Average INTEGER,
  Provincial_Science_Average INTEGER,
  Provincial_History_Average INTEGER,
  Provincial_Physical_Education_Average INTEGER,
  Provincial_Arts_Music_Average INTEGER,
  Provincial_ERC_Average INTEGER,

  Number_of_Clubs INTEGER,
  Cumulative_Years_in_Clubs INTEGER,
  Years_In_Leadership_Positions INTEGER,
  Debate_Club_Years INTEGER,
  Dance_Years INTEGER,
  MUN_Years INTEGER,
  Music_Clubs_Years INTEGER,
  Tutoring_Clubs_Years INTEGER,
  Local_Service_Clubs_Years INTEGER,
  International_Service_Clubs_Years INTEGER,

  Number_of_Sports INTEGER,
  Cumulative_Years_in_Sports INTEGER,
  Individual_Sports INTEGER,
  Team_Sports INTEGER,

  Number_of_Detentions INTEGER,
  Number_of_Suspensions INTEGER,
  Number_of_Expulsions INTEGER,
  Number_of_Failed_Classes INTEGER,
  Number_of_Summer_School_Classes INTEGER,
  Criminal_Record BOOLEAN,
  Attendance_Percentage INTEGER,

  School_Awards INTEGER,
  Volunteering_Hours INTEGER,
  Working_Hours INTEGER,
  Number_Of_Enriched_Classes INTEGER,
  Number_Of_Languages_Spoken INTEGER,

  Number_Of_Immediate_Family INTEGER,
  Parent_Relationship_Status TEXT,
  Number_Of_Siblings INTEGER,
  Family_Economic_Status INTEGER,
  Mother_Race TEXT,
  Father_Race TEXT
);

DESC students;

/* 1 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('Laura Pelletier', '2001-05-25', 2018, 'Female', 'H2C1A6', 77, 65, 78, 69, 72, 84, 87, 91, 77, 9.1, 82, 87, 84, 77, 77, 88, 85, 90, 83, 85, 81, 71, 73, 84, 86, 92, 75, 81, 86, 76, 73, 74, 82, 84, 83, 79, 78, 77, 75, 72, 78, 83, 85, 76, 81, 77, 75, 72, 71, 76, 81, 81, 74, 79, 1, 1, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 5,
0, 0, 0, 0, False, 86, 0, 0, 0, 0, 2, 4, 'Married', 2, 8, 'Caucasian', 'Caucasian');

/* 2 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('John Pham', '2001-01-25', 2018, 'Male', 'H4S3K8', 78, 83, 74, 87, 81, 76, 89, 74, 84, 9.1, 83, 81, 84, 76, 84, 79, 85, 76, 87, 81, 78, 80, 79, 83, 82, 81, 82, 84, 79, 83, 80, 86, 83, 84, 78, 77, 75, 72, 78, 83, 85, 72, 73, 76, 81, 77, 75, 72, 71, 76, 81, 81, 74, 79, 1, 1, 0, 0, 1, 2, 0, 0, 3, 1, 2, 4, 1, 1, 5,
1, 0, 1, 1, False, 97, 0, 20, 0, 0, 2, 3, 'Married', 1, 6, 'Vietnamese', 'Vietnamese');

/* 3 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('Zahia Aliouleche', '2001-03-17', 2018, 'Female', 'H3D7Y2', 79, 74, 81, 77, 76, 83, 72, 74, 78, 9.1, 82, 79, 81, 84, 79, 83, 80, 81, 83, 83, 78, 83, 81, 79, 82, 80, 82, 81, 82, 77, 78, 76, 84, 85, 78, 81, 78, 77, 75, 72, 78, 83, 85, 76, 81, 77, 75, 72, 71, 76, 81, 81, 74, 79, 2, 4, 1, 0, 0, 0, 0, 0, 2, 1, 1, 3, 1, 0, 2,
0, 0, 0, 0, False, 89, 0, 10, 0, 0, 3, 4, 'Married', 2, 6, 'Algerian', 'Algerian');

/* 4 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('Philippe Voyer-Nguyen', '2001-06-30', 2018, 'Male', 'H2C2V5', 95, 97, 87, 97, 96, 86, 89, 95, 86, 9.1, 79, 93, 78, 75, 77, 87, 85, 92, 78, 94, 79, 73, 74, 83, 86, 92, 78, 81, 83, 76, 73, 79, 84, 85, 89, 82, 78, 77, 75, 72, 78, 83, 85, 76, 81, 77, 75, 72, 71, 76, 81, 81, 74, 79, 3, 5, 0, 0, 0, 0, 5, 1, 0, 1, 1, 2, 1, 0, 0,
0, 0, 0, 0, False, 98, 27, 124, 10, 8, 2, 3, 'Married', 1, 8, 'Vietnamese', 'Caucasian');

/* 5 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('Zakaria Benmammar', '2001-09-29', 2018, 'Male', 'H2N1E7', 77, 73, 74, 86, 85, 72, 79, 76, 74, 9.1, 76, 75, 73, 74, 75, 80, 84, 83, 78, 77, 74, 76, 75, 82, 81, 83, 79, 79, 73, 74, 75, 75, 78, 79, 78, 77, 78, 77, 75, 72, 78, 83, 85, 76, 81, 77, 75, 72, 71, 76, 81, 81, 74, 79, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 8,
0, 0, 0, 0, False, 93, 1, 10, 40, 3, 3, 4, 'Married', 2, 7, 'Algerian', 'Algerian');

/* 6 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('Jacky Lu-Trinh', '2001-01-08', 2018, 'Male', 'H4M2J1', 84, 89, 78, 85, 80, 82, 90, 83, 83, 9.1, 82, 87, 76, 82, 81, 82, 87, 85, 80, 84, 82, 84, 82, 80, 85, 82, 81, 78, 81, 78, 80, 76, 75, 83, 81, 82, 78, 77, 75, 72, 78, 83, 85, 76, 81, 77, 75, 72, 71, 76, 81, 81, 74, 79, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
0, 0, 0, 0, False, 95, 5, 80, 0, 7, 3, 4, 'Married', 2, 8, 'Vietnamese', 'Vietnamese');

/* 7 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('Amine Menard', '2000-11-06', 2018, 'Male', 'H4Q7M9', 71, 83, 68, 65, 71, 80, 82, 61, 63, 9.1, 78, 93, 77, 73, 78, 81, 82, 77, 73, 92, 75, 76, 77, 79, 83, 77, 78, 78, 87, 77, 75, 76, 80, 83, 79, 72, 78, 77, 75, 72, 78, 83, 85, 76, 81, 77, 75, 72, 71, 76, 81, 81, 74, 79, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 5, 0, 1, 11,
1, 0, 1, 2, True, 71, 0, 2, 0, 3, 3, 3, 'Married', 1, 6, 'Arabic', 'French');

/* 8 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('Naomi Panetta', '2000-10-09', 2018, 'Female', 'H7E5N8', 80, 93, 70, 73, 72, 83, 85, 94, 74, 9.1, 78, 93, 74, 75, 74, 79, 82, 89, 77, 88, 74, 73, 75, 85, 82, 84, 76, 76, 83, 74, 71, 72, 80, 82, 75, 75, 78, 75, 71, 72, 75, 80, 82, 77, 77, 77, 75, 72, 71, 74, 81, 81, 74, 79, 4, 2, 1, 1, 6, 0, 5, 0, 1, 1, 2, 5, 1, 1, 3,
0, 0, 0, 0, False, 78, 4, 18, 0, 5, 3, 4, 'Married', 2, 7, 'Italian', 'Italian');

/* 9 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('Sarun Santino', '2000-11-05', 2018, 'Male', 'H4M5H2', 72, 75, 68, 65, 63, 78, 82, 61, 76, 5.4, 68, 64, 62, 70, 61, 72, 73, 70, 74, 72, 68, 67, 70, 71, 76, 73, 74, 70, 68, 66, 70, 71, 67, 74, 63, 67, 78, 77, 75, 72, 78, 83, 85, 76, 81, 77, 75, 72, 71, 76, 81, 81, 74, 79, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 2, 4, 0, 2, 9,
2, 0, 2, 1, False, 72, 0, 0, 70, 0, 3, 5, 'Married', 2, 4, 'Indian', 'Indian');

/* 10 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('Alexander Achcar', '2000-02-29', 2017, 'Male', 'H0H0H0', 59, 71, 55, 62, 60, 72, 59, 49, 51, 4.1, 65, 67, 70, 57, 61, 66, 70, 61, 62, 60, 71, 58, 60, 67, 73, 66, 68, 66, 65, 72, 59, 57, 63, 74, 71, 63, 78, 77, 75, 72, 78, 80, 81, 76, 79, 77, 75, 72, 71, 76, 81, 81, 74, 79, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10,
2, 1, 3, 4, True, 47, 0, 0, 60, 0, 2, 5, 'Married', 3, 5, 'Caucasian', 'Caucasian');

/* 11 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('JiaQi Zhao', '1998-09-22', 2020, 'Female', 'H3Y 1X2', 91, 87, 90, 95, 96, 99, 90, 92, 87, 8.1, 78, 75, 80, 76, 81, 76, 85, 90, 80, 76, 70, 83, 76, 73, 84, 78, 75, 78, 75, 78, 73, 76, 78, 82, 80, 76, 80, 76, 79, 69, 67, 76, 81, 78, 72, 72, 71, 82, 71, 73, 76, 80, 74, 73, 3, 2, 0, 0, 3, 0, 5, 1, 3, 0, 2, 3, 2, 1, 0,
0, 0, 0, 0, False, 99, 10, 200, 59, 3, 3, 3, 'Married', 1, 7, 'Chinese', 'Chinese');

/* 12 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('Edward Habelrih', '2001-01-13', 2018, 'Male', 'H4O8S3', 97, 96, 95, 99, 99, 98, 94, 95, 97, 10.0, 87, 85, 83, 92, 93, 91, 86, 83, 89, 88, 86, 90, 89, 87, 84, 86, 88, 83, 84, 81, 80, 81, 87, 84, 83, 84, 78, 77, 75, 72, 78, 85, 85, 76, 81, 77, 75, 72, 71, 76, 81, 81, 74, 79, 3, 4, 2, 2, 0, 1, 2, 1, 1, 2, 1, 3, 1, 0, 0,
0, 0, 0, 0, False, 99, 32, 230, 56, 8, 3, 2, 'Married', 0, 7, 'Caucasian', 'Caucasian');

/* 13 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('James Iafigliola', '2001-06-22', 2018, 'Male', 'H4S077K1', 87, 90, 83, 85, 82, 94, 80, 83, 89, 8.4, 79, 80, 78, 76, 78, 82, 84, 80, 75, 76, 74, 73, 71, 72, 80, 79, 76, 77, 74, 71, 79, 77, 78, 80, 76, 78, 78, 77, 75, 72, 78, 83, 85, 76, 81, 77, 75, 72, 71, 76, 81, 81, 74, 79, 2, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
0, 0, 0, 0, False, 98, 14, 24, 0, 5, 3, 3, 'Married', 1, 8, 'Italian', 'Italian');

/* 14 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('Samantha Barber', '2000-01-25', '2018', 'Female', 'H5A6B3', 73, 78, 76, 68, 65, 77, 70, 80, 71, 8.6, 70, 74, 73, 64, 66, 71, 72, 68, 67, 71, 73, 70, 69, 74, 74, 68, 70, 70, 73, 71, 65, 64, 74, 75, 72, 70, 78, 77, 75, 72, 78, 83, 85, 76, 81, 77, 75, 72, 71, 76, 81, 81, 74, 79, 2, 2, 1, 1, 2, 1, 1, 0, 2, 2, 1, 5, 0, 1, 4,
0, 0, 1, 1, False, 68, 2, 6, 0, 3, 2, 2, 'Married', 0, 8, 'Greek', 'Greek');

/* 15 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('Zu Yi Chang', '2000-10-29', 2018, 'Female', 'H4E6B7', 55, 70, 61, 53, 50, 58, 62, 32, 55, 8.6, 78, 76, 77, 76, 78, 77, 81, 79, 75, 77, 76, 80, 79, 75, 80, 79, 74, 79, 79, 78, 82, 76, 77, 83, 81, 83, 78, 77, 75, 72, 78, 83, 83, 76, 81, 77, 75, 72, 71, 76, 81, 81, 74, 79, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14,
5, 1, 5, 2, False, 43, 0, 0, 0, 0, 2, 2, 'Divorced', 0, 10, 'Chinese', 'Chinese');

/* 16 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('Schnaica Davis', '2001-04-03', 2018, 'Female', 'H2A9F4', 72, 78, 67, 74, 73, 68, 80, 65, 79, 6.3, 74, 72, 74, 68, 65, 75, 83, 81, 70, 74, 75, 77, 73, 76, 80, 79, 82, 78, 77, 73, 80, 77, 78, 83, 69, 75, 78, 77, 75, 72, 78, 83, 85, 76, 81, 77, 75, 72, 71, 76, 81, 81, 74, 79, 4, 10, 3, 1, 2, 2, 5, 0, 2, 1, 0, 0, 0, 0, 2,
0, 0, 2, 2, False, 78, 2, 89, 34, 0, 2, 5, 'Married', 3, 6, 'African-American', 'Haitian');

/* 17 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('Valerie Piccard', '2001-02-09', 2018, 'Female', 'H4Q7I4', 86, 89, 84, 87, 88, 85, 92, 83, 82, 8.9, 82, 83, 80, 86, 84, 78, 76, 79, 84, 84, 80, 85, 84, 79, 81, 80, 82, 80, 82, 79, 83, 82, 77, 83, 76, 79, 78, 77, 75, 72, 78, 83, 85, 76, 81, 77, 75, 72, 71, 76, 81, 81, 74, 79, 4, 13, 2, 1, 0, 3, 0, 3, 2, 2, 2, 5, 1, 1, 0,
0, 0, 0, 0, False, 98, 3, 76, 40, 7, 2, 4, 'Divorced', 2, 9, 'Mexican', 'Caucasian');

/* 18 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('Alexandra Rénaud', '2000-11-26', 2018, 'Non-binary', 'H2H5J7', 80, 78, 82, 76, 74, 87, 72, 84, 87, 7.8, 83, 80, 84, 85, 82, 78, 79, 80, 77, 81, 79, 80, 84, 82, 80, 79, 81, 75, 77, 78, 73, 72, 80, 74, 76, 74, 78, 77, 75, 72, 78, 83, 85, 76, 81, 77, 75, 72, 71, 76, 81, 81, 74, 79, 3, 7, 2, 2, 0, 4, 0, 0, 0, 1, 1, 3, 0, 1, 4,
0, 0, 0, 0, False, 92, 4, 30, 16, 2, 2, 2, 'Married', 0, 6, 'African-American', 'Caucasian');

/* 19 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('Evan Zhang', '2001-06-17', 2020, 'Male', 'J0L2K0', 52, 32, 99, 71, 71, 98, 69, 82, 72, 10.0, 85, 81, 83, 85, 86, 83, 81, 83, 83, 85, 81, 78, 79, 75, 80, 80, 81, 85, 81, 85, 82, 84, 81, 86, 80, 81, 76, 73, 74, 71, 70, 81, 81, 82, 80, 74, 72, 75, 71, 69, 73, 81, 82, 75, 3, 5, 0, 1, 7, 0, 0, 3, 2, 1, 3, 2, 1, 1, 10,
1, 0, 0, 1, False, 97, 0, 0, 10, 2, 3, 2, 'Married', 0, 6, 'Chinese', 'Chinese');

/* 20 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('Leonardo Pavinci', '2000-12-17', 2018, 'Male', 'H1K0L2', 74, 76, 75, 69, 65, 79, 95, 71, 77, 6.1, 73, 72, 70, 74, 69, 75, 74, 68, 71, 75, 76, 74, 75, 77, 79, 74, 73, 79, 78, 74, 76, 73, 78, 81, 82, 80, 78, 77, 75, 72, 78, 83, 85, 76, 81, 77, 75, 72, 71, 76, 81, 81, 74, 79, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 10, 1, 2, 11,
2, 0, 0, 0, False, 84, 5, 0, 79, 0, 2, 3, 'Divorced', 1, 7, 'Caucasian', 'Caucasian');

/* 21 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('Henry Zhou', '2001-05-25', 2020, 'Male', 'H4L3M3', 93, 94, 79, 92, 96, 95, 78, 75, 83, 10.0, 75, 76, 79, 79, 79, 85, 80, 75, 76, 80, 79, 82, 78, 87, 77, 75, 72, 87, 79, 87, 88, 85, 81, 80, 80, 80, 82, 79, 82, 77, 75, 72, 82, 78, 78, 70, 71, 75, 72, 73, 75, 78, 71, 68, 2, 1, 0, 0, 5, 1, 1, 0, 0, 0, 1, 11, 1, 0, 8,
0, 0, 0, 0, False, 95, 10, 250, 120, 0, 4, 4, 'Married', 2, 6, 'Chinese', 'Chinese');

/* 22 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('Samuel Lin', '2001-02-17', 2018, 'Male', 'H0H0H0', 90, 50, 91, 92, 87, 89, 85, 99, 87, 10.0, 87, 85, 87, 82, 85, 79, 81, 80, 82, 80, 82, 83, 86, 82, 81, 83, 87, 90, 87, 88, 85, 87, 82, 84, 85, 86, 76, 70, 73, 72, 69, 70, 80, 81, 82, 76, 70, 74, 72, 74, 72, 75, 78, 81, 2, 2, 0, 0, 0, 2, 12, 0, 2, 0, 0, 0, 0, 0, 2,
0, 0, 0, 0, False, 99, 12, 130, 70, 0, 2, 3, 'Married', 1, 9, 'Chinese', 'Chinese');

/* 23 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('Jean Baptiste', '2000-12-20', 2020, 'Male', 'J309R8', 87, 78, 74, 82, 75, 87, 86, 84, 85, 9.8, 84, 81, 74, 76, 78, 77, 76, 82, 74, 77, 76, 77, 75, 82, 83, 75, 78, 80, 81, 79, 78, 84, 85, 80, 80, 75, 78, 79, 83, 79, 82, 76, 77, 80, 81, 80, 80, 78, 79, 76, 77, 79, 81, 79, 4, 3, 4, 2, 0, 0, 4, 6, 2, 3, 4, 3, 0, 2, 0,
0, 0, 0, 2, 0, 98, 2, 110, 90, 0, 3, 4, 'Married', 2, 7, 'Caucasian', 'Caucasian');

/* 24 */
INSERT INTO students (Name, Date_of_Birth, Graduating_Year, Gender, Postal_Code, Personal_Cumulative_Grade_Average, Personal_English_Average, Personal_French_Average, Personal_Math_Average, Personal_Science_Average, Personal_History_Average, Personal_Physical_Education_Average, Personal_Arts_Music_Average, Personal_ERC_Average, High_School_Rating, Class_Cumulative_Grade_Average, Class_English_Average, Class_French_Average, Class_Math_Average, Class_Science_Average, Class_History_Average, Class_Physical_Education_Average, Class_Arts_Music_Average, Class_ERC_Average, Teacher_English_Average, Teacher_French_Average, Teacher_Math_Average, Teacher_Science_Average, Teacher_History_Average, Teacher_Physical_Education_Average, Teacher_Arts_Music_Average, Teacher_ERC_Average, School_Cumulative_Grade_Average, School_English_Average, School_French_Average, School_Math_Average, School_Science_Average, School_History_Average, School_Physical_Education_Average, School_Arts_Music_Average, School_ERC_Average, Region_Cumulative_Grade_Average, Region_English_Average, Region_French_Average, Region_Math_Average, Region_Science_Average, Region_History_Average, Region_Physical_Education_Average, Region_Arts_Music_Average, Region_ERC_Average, Provincial_Cumulative_Grade_Average, Provincial_English_Average, Provincial_French_Average, Provincial_Math_Average, Provincial_Science_Average, Provincial_History_Average, Provincial_Physical_Education_Average, Provincial_Arts_Music_Average, Provincial_ERC_Average, Number_of_Clubs, Cumulative_Years_in_Clubs, Years_In_Leadership_Positions, Debate_Club_Years, Dance_Years, MUN_Years, Music_Clubs_Years, Tutoring_Clubs_Years, Local_Service_Clubs_Years, International_Service_Clubs_Years, Number_of_Sports, Cumulative_Years_in_Sports, Individual_Sports, Team_Sports, Number_of_Detentions,
Number_of_Suspensions, Number_of_Expulsions, Number_of_Failed_Classes, Number_of_Summer_School_Classes, Criminal_Record, Attendance_Percentage, School_Awards, Volunteering_Hours, Working_Hours, Number_Of_Enriched_Classes, Number_Of_Languages_Spoken, Number_Of_Immediate_Family, Parent_Relationship_Status, Number_Of_Siblings, Family_Economic_Status, Mother_Race, Father_Race)
VALUES ('Yinan Zhao', '2000-10-15', 2020, 'Male', 'H3Y1X9', 90, 87, 88, 98, 95, 84, 96, 98, 87, 7.2, 80, 76, 74, 79, 79, 76, 83, 82, 82, 75, 76, 79, 78, 82, 83, 81, 83, 80, 78, 76, 82, 84, 80, 78, 82, 81, 78, 78, 80, 72, 70, 72, 80, 82, 76, 74, 73, 77, 72, 71, 78, 83, 81, 78, 5, 2, 1, 1, 0, 0, 5, 2, 2, 1, 2, 5, 0, 2, 0,
0, 0, 0, 0, False, 97, 10, 120, 0, 3, 3, 3, 'Married', 1, 7, 'Chinese', 'Chinese');